#!/bin/bash

# just for wsl2 env

dir="/opt/wsl-crashes/"

if [[ ! -d "$dir" ]]; then
    echo "Error: $dir is not a valid dir"
    exit 1
fi

latest_file=$(find "$dir" -type f -printf '%T@ %p\n' 2>/dev/null | sort -n | tail -1 | cut -d' ' -f2-)

if [[ -z "$latest_file" ]]; then
    echo ""
    exit 1
fi

echo "$latest_file"

